<body>
    <div class="resolucion">    
        <div class="desktop">  
            <!-- ID Particles.js -->
            <div id="particles-js"></div>
            <header class="contenedor header">
              <!-- Título y descripción -->
             <div class="contenido-descripcion">
                    <div>
                        <a href="index1.html" style="text-decoration:none" <div class="sign">F<span class="fast-flicker">1</span>R<span class="flicker">0</span>X</div></a>
                    </div>
                </div>
            </header>

            <!-- JS Particles.js -->
            <script src="js/particles.min.js"></script>
            <script src="js/app.js"></script>
            <!-- JS FontAwesome -->
            <script src="https://kit.fontawesome.com/a2e8d0339c.js"></script>
        </div>
        <div class="tablet">  
             <!-- ID Particles.js -->
            <div id="particles-js"></div>
            <header class="contenedor header">
              <!-- Título y descripción -->
             <div class="contenido-descripcion">
                    <div>
                        <a href="index1.html" style="text-decoration:none" <div class="sign">F<span class="fast-flicker">1</span>R<span class="flicker">0</span>X</div></a>
                    </div>
                </div>
            </header>

            <!-- JS Particles.js -->
            <script src="js/particles.min.js"></script>
            <script src="js/app.js"></script>
            <!-- JS FontAwesome -->
            <script src="https://kit.fontawesome.com/a2e8d0339c.js"></script>      
        
            
        </div>
        <div class="movil">
             <!-- ID Particles.js -->
            <div id="particles-js"></div>
            <header class="contenedor header">
              <!-- Título y descripción -->
             <div class="contenido-descripcion">
                    <div>
                        <a href="index1.html" style="text-decoration:none" <div class="sign">F<span class="fast-flicker">1</span>R<span class="flicker">0</span>X</div></a>
                    </div>
                </div>
            </header>

            <!-- JS Particles.js -->
            <script src="js/particles.min.js"></script>
            <script src="js/app.js"></script>
            <!-- JS FontAwesome -->
            <script src="https://kit.fontawesome.com/a2e8d0339c.js"></script>
        
        </div>    
    </div>
</body>
